### ISSUE TITLE
Add a Spidertron and related equipment?

### ISSUE THREAD

**Issue by mw-stanley** [fangxianfu/factorio-quick-start#4]
Requested on Factorio forums: https://mods.factorio.com/mod/crash-quick-start/discussion/5f39d446805c4073f48f633d

Could add spidertron & related equipment.

I think my preference is to have a tickbox to add a spidertron to any of the presets rather than it being part of any of the existing presets.

**Comment by mw-stanley** [comment]
What would be good to include in a "spidertron kit"? Spidertron, remote, some logistics stuff?

**Comment by mw-stanley** [comment]
Proposed inventory:

- 1 spidertron
- 1 spidertron-remote
- 50 additional construction-robot
- 1 additional fusion-reactor-equipment
- 5 additional personal-roboport-equipment
- 3 additional battery-equipment

This would require a change to the code that adds the items to update the value rather than setting the value https://github.com/fangxianfu/factorio-quick-start/blob/b16930da5d0213fd605e2ddb2f404262e9a0b46c/control.lua#L155

**Comment by Hecatia-Lapislazuli** [comment]
Seems good, maybe a bit less personal roboports though... three maybe? Have two battery equipment as well, and maybe add one shield and an exoskeleton. Optionally, have an option to do a more balanced version with portable fusion reactor replaced with 16 solar panels and another two batteries.

Not too sure on balance for that, would be op either way but trying not to trivialize the bitter threat, y'know? Only reason I'd say don't add rockets or personal lasers is because of that. Could be potential for another option to enable there, however. Not sure how much you're wanting to do those, though.

**Comment by mw-stanley** [comment]
With this change, I'm basically just trying to hit enough stuff to make the spidertron useful. If the player thinks it's unethical they have the option to not use any of the stuff it grants. The amounts are the exact same amount that's given on the Medium and Big settings for the player to use themselves.

Philosophically, I don't really think balance is worth worrying about too much. This mod is inherently unbalancing - the objective is to remove some the tedium from the early game. 

Re rockets though, yes I think leaving them out is the right idea. I don't think it would really be practical to give the player enough rockets to get them all the way to when they can produce their own. But there are lots of good options already in the game or in other mods to mitigate the tedium of biters if the player wants to do that.
